version: '3'

services:
  app:
    build:
      args:
        user: indifin-user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: indifin-php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker-compose/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:rw,delegated
    networks:
      - indifin

  db:
    image: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
      # If you want to persist data on the host, comment the line above this one...
      # and uncomment the line under this one.
      #- ./docker-compose/db/data:/var/lib/mysql:rw,delegated
    environment:
      MYSQL_USER: indifin
      MYSQL_PASSWORD: indifin
      MYSQL_DATABASE: indifin
      MYSQL_ROOT_PASSWORD: indifin
    ports:
      - '33006:3306'
    networks:
      - indifin

  nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - indifin

  cron:
    build:
      context: ./
      dockerfile: ./docker-compose/cron.dockerfile
    volumes:
      - ./:/var/www
    networks:
      - indifin

volumes:
  db:

networks:
  indifin:
    driver: bridge
